"""add lat_lng_conductor to viajes

Revision ID: 544dd05bd761
Revises: 
Create Date: 2026-04-27 21:59:25.223080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544dd05bd761'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_evaluacion'), 'evaluaciones', type_='unique')
    op.drop_index(op.f('unique_evaluacion_idx'), table_name='evaluaciones')
    op.create_foreign_key(None, 'evaluaciones', 'viajes', ['viaje_id'], ['id'])
    op.create_foreign_key(None, 'mensajes', 'viajes', ['viaje_id'], ['id'])
    op.create_foreign_key(None, 'ofertas', 'viajes', ['viaje_id'], ['id'])
    op.drop_constraint(op.f('usuarios_token_unique'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_token'), 'usuarios', ['token'], unique=True)
    op.add_column('viajes', sa.Column('lat_conductor', sa.Float(), nullable=True))
    op.add_column('viajes', sa.Column('lng_conductor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viajes', 'lng_conductor')
    op.drop_column('viajes', 'lat_conductor')
    op.drop_index(op.f('ix_usuarios_token'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_token_unique'), 'usuarios', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.create_index(op.f('unique_evaluacion_idx'), 'evaluaciones', ['viaje_id', 'evaluador_id'], unique=True)
    op.create_unique_constraint(op.f('unique_evaluacion'), 'evaluaciones', ['viaje_id', 'evaluador_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
